@URL=http://localhost:3000/api/posts


###
# @desc  Get all posts
# @route  GET api/posts
GET {{URL}}

###
# @desc  Get One post
# @route  GET api/posts/:id
GET {{URL}}

###
# @desc  Create a post
# @route  POST api/posts
POST {{URL}}
Content-Type: application/json

{
  "title": "Post 11",
  "body": "Post 11 body"
}

###
# @desc  Update a post
# @route  PATCH api/posts/:id
PATCH  {{URL}}/:id
Content-Type: application/json

{
  "title": "Post 11",
  "body": "Post 11 body!"
}

###
# @desc  Delete a post
# @route  DELETE api/posts/:id
DELETE {{URL}}/:id
